mixin () {
  /// Static Markdown documentation of the backend's public API.
  public query func getApiDoc() : async Text {
    "## Career Trial — Backend API\n\n"
    # "Backend cho ứng dụng **Career Trial**: một bài trải nghiệm nghề nghiệp (hiện tại là «Chuyên viên Marketing») gồm danh sách nhiệm vụ tương tác, câu hỏi kiểm tra nhanh, ghi chú tự suy ngẫm, nhận xét mức độ phù hợp và một chat box tư vấn mentor.\n\n"
    # "## Xác thực (Authentication)\n\n"
    # "- Mọi phương thức đều nhận `caller` từ Internet Identity. Không có phương thức nào yêu cầu đăng nhập bắt buộc: người dùng ẩn danh (anonymous) vẫn gọi được và có tiến độ riêng theo principal ẩn danh của phiên đó.\n"
    # "- Frontend ghim một **derivation origin** cho Internet Identity, công bố tại `/.well-known/ii-derivation-origin`. Một agent đã có uỷ quyền Internet Identity của người dùng sẽ suy ra đúng principal theo ứng dụng khi dùng origin đó, ví dụ `icp identity link web <name> --app <host>`. Lưu ý: uỷ quyền này hành động với toàn bộ quyền của người dùng trong ứng dụng này cho tới khi hết hạn.\n"
    # "- Principal suy ra theo một origin khác là một principal **khác** với principal mà frontend đã dùng, nên tiến độ sẽ không được chia sẻ giữa hai principal đó.\n\n"
    # "## Phân quyền (Authorization)\n\n"
    # "- Không có vai trò admin/owner cho các endpoint nghiệp vụ. Mọi endpoint thao tác trên tiến độ đều chỉ đọc/ghi bản ghi của chính `caller`.\n"
    # "- `getTrial`, `getProgress`, `getMentorMessages`, `getAssessment` là các truy vấn chỉ đọc (`query`).\n"
    # "- `setStepCompleted`, `setAnswer`, `setReflection`, `sendMentorMessage` là các cập nhật (`update`) và ghi vào tiến độ của `caller`.\n"
    # "- Truy vấn OQL (`schema`, `execute`) được cấp quyền theo từng bảng: bảng `progress` dùng mức `controllerOrScoped` — controller đọc tất cả, người dùng đã đăng nhập chỉ đọc đúng dòng của mình (cột `owner`).\n\n"
    # "## Đơn vị và mã hoá (Units & encoding)\n\n"
    # "- `Timestamp` là **nanoseconds kể từ epoch**, kiểu `Int`, lấy từ `Time.now()`.\n"
    # "- `StepId`, `TaskId`, `QuestionId`, `MessageId` là `Nat`.\n"
    # "- `answers` là mảng các cặp `(QuestionId, Nat)` — `Nat` là **chỉ số** của lựa chọn trong `Question.options` (bắt đầu từ 0).\n"
    # "- `reflections` là mảng các cặp `(QuestionId, Text)`.\n"
    # "- `ChatRole` là variant `#user` / `#mentor`.\n"
    # "- `FitLevel` là variant `#strong` / `#moderate` / `#developing`.\n"
    # "- `assessment` là `?Assessment` — `null` cho tới khi bài trải nghiệm hoàn thành.\n"
    # "- `getApiDoc` trả về Markdown tĩnh, không phản ánh trạng thái runtime.\n\n"
    # "## Vòng đời và polling (Lifecycle & polling)\n\n"
    # "- `getTrial()` trả về định nghĩa bài trải nghiệm (tiêu đề, danh sách nhiệm vụ với các bước, danh sách câu hỏi kiểm tra nhanh) **kèm** tiến độ hiện tại của `caller`.\n"
    # "- Tiến độ được lưu theo principal của người gọi. Người gọi mới nhận một bản ghi tiến độ rỗng (`completedSteps = []`, `answers = []`, `reflections = []`, `messages = []`, `assessment = null`).\n"
    # "- Một nhiệm vụ được coi là hoàn thành khi **mọi bước** của nó đã được tích.\n"
    # "- Bài trải nghiệm hoàn thành khi tất cả nhiệm vụ đã xong **và** tất cả câu hỏi kiểm tra nhanh đã được trả lời.\n"
    # "- `getAssessment()` trả về `null` cho tới khi bài trải nghiệm hoàn thành. Sau đó trả về nhận xét mức độ phù hợp dựa trên chính kết quả người dùng đã làm.\n"
    # "- Frontend nên polling bằng cách gọi lại `getProgress()` (hoặc `getTrial()`) sau mỗi thao tác ghi; các hàm ghi đều trả về tiến độ đã cập nhật nên thường không cần gọi lại ngay.\n\n"
    # "## An toàn khi thử lại (Mutation retry safety)\n\n"
    # "- `setStepCompleted(stepId, completed)` là **idempotent**: tích một bước đã tích hoặc bỏ tích một bước chưa tích đều không tạo bản ghi trùng.\n"
    # "- `setAnswer(questionId, optionIndex)` và `setReflection(questionId, note)` là **idempotent theo câu hỏi**: gọi lại sẽ thay thế giá trị cũ của cùng câu hỏi, không thêm mục trùng.\n"
    # "- `sendMentorMessage(text)` **không idempotent**: mỗi lần gọi đều thêm một lượt người dùng và một lượt trả lời của mentor vào lịch sử chat. Không tự động thử lại khi gặp lỗi mạng, vì có thể tạo tin nhắn trùng.\n"
    # "- Không có thao tác nào xoá dữ liệu của người khác; không có endpoint phá huỷ (destructive) nào.\n\n"
    # "## Lỗi và giới hạn (Errors & limits)\n\n"
    # "- Các hàm không trả về `Result`; chúng trả về tiến độ hoặc giá trị đã cập nhật.\n"
    # "- `getAssessment()` trả `null` (không trap) khi bài trải nghiệm chưa hoàn thành.\n"
    # "- Không có giới hạn độ dài văn bản được áp đặt ở backend cho ghi chú tự suy ngẫm hay tin nhắn mentor; frontend nên tự giới hạn để tránh payload quá lớn.\n"
    # "- `sendMentorMessage` trả về **lượt trả lời của mentor**, không phải toàn bộ lịch sử; dùng `getMentorMessages()` để lấy toàn bộ lịch sử theo thứ tự cũ → mới.\n\n"
    # "## Lưu ý tích hợp (Gotchas)\n\n"
    # "- **`getAssessment` là một `query` và không lưu kết quả.** Nó tính lại nhận xét từ tiến độ hiện tại mỗi lần gọi (deterministic), nên kết quả có thể thay đổi nếu tiến độ thay đổi, và `createdAt` trong nhận xét là thời điểm tính toán.\n"
    # "- **Tiến độ được khoá theo principal của người gọi.** Cùng một người dùng trên hai origin/principal khác nhau sẽ thấy hai tiến độ khác nhau.\n"
    # "- Tiến độ **không** được lưu theo tài khoản người dùng ở tầng ứng dụng; nó gắn với principal Internet Identity đang gọi.\n"
    # "- Bảng OQL `progress` chỉ phơi ra các **số đếm** (`completedSteps`, `answers`, `reflections`, `messages`) và cờ `hasAssessment`, không phơi nội dung văn bản.\n";
  };
};
