/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'suggestions' : Array<string>,
  'strengths' : Array<string>,
  'fitLevel' : FitLevel,
  'improvements' : Array<string>,
  'createdAt' : Timestamp,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'id' : MessageId,
  'createdAt' : Timestamp,
  'role' : ChatRole,
  'text' : string,
}
export type ChatRole = { 'mentor' : null } |
  { 'user' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FitLevel = { 'strong' : null } |
  { 'developing' : null } |
  { 'moderate' : null };
export type MessageId = bigint;
export interface Question {
  'id' : QuestionId,
  'order' : bigint,
  'prompt' : string,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Step { 'id' : StepId, 'title' : string, 'order' : bigint }
export type StepId = bigint;
export interface Task {
  'id' : TaskId,
  'title' : string,
  'order' : bigint,
  'steps' : Array<Step>,
}
export type TaskId = bigint;
export type Timestamp = bigint;
export interface TrialProgress {
  'assessment' : [] | [Assessment],
  'messages' : Array<ChatMessage>,
  'answers' : Array<[QuestionId, bigint]>,
  'reflections' : Array<[QuestionId, string]>,
  'completedSteps' : Array<StepId>,
}
export interface TrialView {
  'tasks' : Array<Task>,
  'title' : string,
  'progress' : TrialProgress,
  'questions' : Array<Question>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / The caller's suitability assessment, or null until the trial is complete.
   */
  'getAssessment' : ActorMethod<[], [] | [Assessment]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / The caller's mentor chat history, oldest first. Read-only.
   */
  'getMentorMessages' : ActorMethod<[], Array<ChatMessage>>,
  /**
   * / The caller's persisted progress. Read-only.
   */
  'getProgress' : ActorMethod<[], TrialProgress>,
  /**
   * / The trial definition plus the caller's progress. Read-only.
   */
  'getTrial' : ActorMethod<[], TrialView>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Send a message to the mentor chat and receive the mentor's reply.
   */
  'sendMentorMessage' : ActorMethod<[string], ChatMessage>,
  /**
   * / Record the caller's selected option for a quick-check question.
   */
  'setAnswer' : ActorMethod<[QuestionId, bigint], TrialProgress>,
  /**
   * / Record the caller's free-text reflection for a quick-check question.
   */
  'setReflection' : ActorMethod<[QuestionId, string], TrialProgress>,
  /**
   * / Tick or untick a step in the caller's progress.
   */
  'setStepCompleted' : ActorMethod<[StepId, boolean], TrialProgress>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];