/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FitLevel = IDL.Variant({
  'strong' : IDL.Null,
  'developing' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Assessment = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'fitLevel' : FitLevel,
  'improvements' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
});
export const MessageId = IDL.Nat;
export const ChatRole = IDL.Variant({ 'mentor' : IDL.Null, 'user' : IDL.Null });
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'createdAt' : Timestamp,
  'role' : ChatRole,
  'text' : IDL.Text,
});
export const QuestionId = IDL.Nat;
export const StepId = IDL.Nat;
export const TrialProgress = IDL.Record({
  'assessment' : IDL.Opt(Assessment),
  'messages' : IDL.Vec(ChatMessage),
  'answers' : IDL.Vec(IDL.Tuple(QuestionId, IDL.Nat)),
  'reflections' : IDL.Vec(IDL.Tuple(QuestionId, IDL.Text)),
  'completedSteps' : IDL.Vec(StepId),
});
export const TaskId = IDL.Nat;
export const Step = IDL.Record({
  'id' : StepId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'steps' : IDL.Vec(Step),
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'order' : IDL.Nat,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const TrialView = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'title' : IDL.Text,
  'progress' : TrialProgress,
  'questions' : IDL.Vec(Question),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMentorMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getProgress' : IDL.Func([], [TrialProgress], ['query']),
  'getTrial' : IDL.Func([], [TrialView], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMentorMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'setAnswer' : IDL.Func([QuestionId, IDL.Nat], [TrialProgress], []),
  'setReflection' : IDL.Func([QuestionId, IDL.Text], [TrialProgress], []),
  'setStepCompleted' : IDL.Func([StepId, IDL.Bool], [TrialProgress], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FitLevel = IDL.Variant({
    'strong' : IDL.Null,
    'developing' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Assessment = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'fitLevel' : FitLevel,
    'improvements' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
  });
  const MessageId = IDL.Nat;
  const ChatRole = IDL.Variant({ 'mentor' : IDL.Null, 'user' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'createdAt' : Timestamp,
    'role' : ChatRole,
    'text' : IDL.Text,
  });
  const QuestionId = IDL.Nat;
  const StepId = IDL.Nat;
  const TrialProgress = IDL.Record({
    'assessment' : IDL.Opt(Assessment),
    'messages' : IDL.Vec(ChatMessage),
    'answers' : IDL.Vec(IDL.Tuple(QuestionId, IDL.Nat)),
    'reflections' : IDL.Vec(IDL.Tuple(QuestionId, IDL.Text)),
    'completedSteps' : IDL.Vec(StepId),
  });
  const TaskId = IDL.Nat;
  const Step = IDL.Record({
    'id' : StepId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'steps' : IDL.Vec(Step),
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'order' : IDL.Nat,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const TrialView = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'title' : IDL.Text,
    'progress' : TrialProgress,
    'questions' : IDL.Vec(Question),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMentorMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getProgress' : IDL.Func([], [TrialProgress], ['query']),
    'getTrial' : IDL.Func([], [TrialView], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMentorMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'setAnswer' : IDL.Func([QuestionId, IDL.Nat], [TrialProgress], []),
    'setReflection' : IDL.Func([QuestionId, IDL.Text], [TrialProgress], []),
    'setStepCompleted' : IDL.Func([StepId, IDL.Bool], [TrialProgress], []),
  });
};

export const init = ({ IDL }) => { return []; };